export const phoneDisplay = "+90 506 472 02 64";
export const phoneHref = "tel:+905064720264";
export const whatsappHref = "https://wa.me/905064720264";

const links = [["Evraklar","/aile-birlesimi-gerekli-evraklar"],["Randevu","/aile-birlesimi-randevusu"],["Tercüme & Apostil","/tercume-apostil-evraklari"],["Haberler","/haberler"],["Blog","/blog"]];
export function Header(){return <header className="nav-wrap"><a className="brand" href="/"><span className="brand-mark">PG</span><span><strong>Pınar Gökalp</strong><small>Uluslararası Başvuru Danışmanlığı</small></span></a><nav>{links.map(([n,h])=><a key={h} href={h}>{n}</a>)}</nav><a className="btn small" href="/on-degerlendirme">Ön Değerlendirme</a></header>}
export function PageHero({eyebrow,title,text}:{eyebrow:string,title:string,text:string}){return <><Header/><section className="page-hero"><p className="eyebrow">{eyebrow}</p><h1>{title}</h1><p>{text}</p></section></>}
export function Disclaimer(){return <section className="independence"><b>Bağımsız danışmanlık açıklaması</b><p>Pınar Gökalp Uluslararası Başvuru Danışmanlığı özel bir danışmanlık hizmetidir. Herhangi bir büyükelçilik, konsolosluk, kamu kurumu veya başvuru merkeziyle resmî bağlantısı bulunmamaktadır. Başvuruların değerlendirilmesi ve nihai karar yalnızca yetkili makamların sorumluluğundadır.</p></section>}
export function ContactBand(){return <section className="contact compact-contact"><p className="eyebrow">Doğru başvuru yolunu birlikte belirleyelim</p><h2>Telefonla<br/><em>ön değerlendirme.</em></h2><p>Kişisel durumunuzu dinleyelim; uygun kategori, evrak ve randevu yol haritanızı oluşturalım.</p><div><a className="btn gold" href={phoneHref}>Hemen Ara: {phoneDisplay}</a><a className="btn outline" href={whatsappHref}>WhatsApp’tan Yaz</a></div></section>}
export function Footer(){return <footer><a className="brand" href="/"><span className="brand-mark">PG</span><span><strong>Pınar Gökalp</strong><small>Uluslararası Başvuru Danışmanlığı</small></span></a><p>Gerçekçi, şeffaf ve kişiye özel başvuru danışmanlığı.</p><div><a href="/iletisim">İletişim</a><a href="/kvkk">KVKK</a><a href="/gizlilik">Gizlilik</a></div><small>© 2026 Pınar Gökalp. Tüm hakları saklıdır.</small></footer>}
export function NumberedCards({items}:{items:{title:string,text:string}[]}){return <section className="editorial-grid numbered-cards">{items.map((x,i)=><article className="editorial-card" key={x.title}><small>{String(i+1).padStart(2,"0")}</small><h2>{x.title}</h2><p>{x.text}</p></article>)}</section>}
